export const exportToPostman = (tests) => {
  const collection = {
    info: {
      name: 'APIBeast Generated Tests',
      description: 'Generated by APIBeast AI',
      schema: 'https://schema.getpostman.com/json/collection/v2.1.0/collection.json'
    },
    item: tests.map(test => ({
      name: test.name,
      request: {
        method: test.method,
        header: Object.entries(test.headers || {}).map(([key, value]) => ({
          key,
          value,
          type: 'text'
        })),
        body: test.body ? {
          mode: 'raw',
          raw: test.body,
          options: {
            raw: {
              language: 'json'
            }
          }
        } : undefined,
        url: {
          raw: test.endpoint,
          protocol: test.endpoint.startsWith('https') ? 'https' : 'http',
          host: test.endpoint.replace(/^https?:\/\//, '').split('/')[0].split('.'),
          path: test.endpoint.replace(/^https?:\/\/[^/]+/, '').split('/').filter(Boolean)
        }
      },
      response: []
    }))
  }
  
  const blob = new Blob([JSON.stringify(collection, null, 2)], { type: 'application/json' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = `APIBeast-Collection-${Date.now()}.postman_collection.json`
  a.click()
  URL.revokeObjectURL(url)
}

export const exportAsJSON = (results, endpoint, method) => {
  const exportData = {
    endpoint,
    method,
    timestamp: new Date().toISOString(),
    totalTests: results.length,
    passed: results.filter(r => r.status === 'passed').length,
    failed: results.filter(r => r.status === 'failed').length,
    results: results
  }
  const blob = new Blob([JSON.stringify(exportData, null, 2)], { type: 'application/json' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = `apibeast-results-${Date.now()}.json`
  a.click()
  URL.revokeObjectURL(url)
}

export const exportAsCSV = (results) => {
  const headers = ['Test Name', 'Status', 'Duration (ms)', 'Response Status', 'Errors']
  const rows = results.map(r => [
    r.test_name,
    r.status,
    r.duration_ms,
    r.response_status || 'N/A',
    r.errors.join('; ')
  ])
  
  const csv = [
    headers.join(','),
    ...rows.map(row => row.map(cell => `"${cell}"`).join(','))
  ].join('\n')
  
  const blob = new Blob([csv], { type: 'text/csv' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = `apibeast-results-${Date.now()}.csv`
  a.click()
  URL.revokeObjectURL(url)
}

export const copyToClipboard = async (results) => {
  const text = results.map(r => 
    `${r.test_name}: ${r.status.toUpperCase()} (${r.duration_ms}ms)${r.errors.length > 0 ? '\n  Errors: ' + r.errors.join(', ') : ''}`
  ).join('\n\n')
  try {
    await navigator.clipboard.writeText(text)
    alert('Results copied to clipboard!')
  } catch (err) {
    alert('Failed to copy to clipboard')
  }
}

export const getPerformanceStats = (results) => {
  if (results.length === 0) return null
  
  const durations = results.map(r => r.duration_ms)
  const passed = results.filter(r => r.status === 'passed').length
  const failed = results.filter(r => r.status === 'failed').length
  
  return {
    total: results.length,
    passed,
    failed,
    passRate: ((passed / results.length) * 100).toFixed(1),
    avgDuration: (durations.reduce((a, b) => a + b, 0) / durations.length).toFixed(0),
    minDuration: Math.min(...durations),
    maxDuration: Math.max(...durations)
  }
}

export const getStatusColor = (status) => {
  switch (status) {
    case 'passed': return 'bg-emerald-500'
    case 'failed': return 'bg-red-500'
    case 'error': return 'bg-amber-500'
    default: return 'bg-slate-500'
  }
}
